# Generated by Django 2.2.18 on 2021-04-28 05:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tea_id', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='123456', max_length=50)),
                ('name', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField(default=datetime.date(2021, 5, 1))),
                ('IDnumber', models.CharField(default='', max_length=20)),
                ('sex', models.CharField(default='', max_length=5)),
                ('entryTime', models.DateField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=5)),
                ('outlook', models.CharField(default='', max_length=10)),
                ('nation', models.CharField(default='', max_length=5)),
                ('native', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='123456', max_length=50)),
                ('name', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField(default=datetime.date(2021, 5, 1))),
                ('IDnumber', models.CharField(default='', max_length=20)),
                ('sex', models.CharField(default='', max_length=5)),
                ('entryTime', models.DateField(auto_now_add=True)),
                ('grade', models.IntegerField()),
                ('outlook', models.CharField(default='', max_length=10)),
                ('nation', models.CharField(default='', max_length=5)),
                ('native', models.CharField(default='', max_length=5)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.ClassInfo')),
            ],
        ),
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.CollegeInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('teacher', models.ManyToManyField(to='adminstrator.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cou_id', models.CharField(default='', max_length=10, unique=True)),
                ('name', models.CharField(default='', max_length=10, unique=True)),
                ('classhour', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('direct', models.CharField(default='', max_length=20, unique=True)),
                ('college', models.CharField(default='', max_length=10, unique=True)),
                ('betyear', models.IntegerField()),
                ('elective', models.BooleanField(default=False)),
                ('form', models.CharField(default='ordinary', max_length=10, unique=True)),
                ('corgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Course_Group')),
            ],
        ),
        migrations.AddField(
            model_name='classinfo',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.MajorInfo'),
        ),
    ]
