# Generated by Django 2.2.18 on 2021-04-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0002_course_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(default=0)),
                ('atitle', models.CharField(max_length=30)),
                ('aParent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
    ]
