# Generated by Django 2.2.18 on 2021-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0003_areainfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='class_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='college_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='majorinfo',
            name='major_id',
            field=models.IntegerField(unique=True),
        ),
    ]
