# Generated by Django 2.2.18 on 2021-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0004_auto_20210501_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorinfo',
            name='major_id',
            field=models.IntegerField(),
        ),
    ]
