# Generated by Django 2.2.18 on 2021-05-01 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0006_auto_20210501_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
