# Generated by Django 2.2.18 on 2021-05-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0007_auto_20210501_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='entryTime',
            field=models.DateField(auto_now=True),
        ),
    ]
