# Generated by Django 2.2.18 on 2021-05-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0008_auto_20210502_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='TeacherInfo',
        ),
    ]
