# Generated by Django 2.2.18 on 2021-05-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0009_auto_20210504_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adm_id', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='123456', max_length=50)),
            ],
        ),
    ]
