# Generated by Django 2.2.18 on 2021-05-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0010_admininfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaInfo',
        ),
    ]
