# Generated by Django 2.2.18 on 2021-05-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0013_cities_countries_provinces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='Provinces',
        ),
    ]
