# Generated by Django 2.2.18 on 2021-05-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0014_auto_20210507_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(default=0)),
                ('atitle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(default=0)),
                ('atitle', models.CharField(max_length=30)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(default=0)),
                ('atitle', models.CharField(max_length=30)),
                ('Province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Provinces')),
            ],
        ),
    ]
