# Generated by Django 2.2.18 on 2021-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0015_cities_countries_provinces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='nation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='native',
            field=models.IntegerField(default=0),
        ),
    ]
