# Generated by Django 2.2.18 on 2021-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0016_auto_20210507_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlook', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='outlook',
            field=models.IntegerField(default=0),
        ),
    ]
