# Generated by Django 2.2.18 on 2021-05-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0018_auto_20210507_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='nation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='native',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='outlook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Outlook'),
        ),
    ]
