# Generated by Django 2.2.18 on 2021-05-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0019_auto_20210507_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlook',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
