# Generated by Django 2.2.18 on 2021-05-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0020_auto_20210507_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlook',
            old_name='outlook',
            new_name='name',
        ),
    ]
