# Generated by Django 2.2.18 on 2021-05-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0021_auto_20210507_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='native',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Cities'),
        ),
    ]
