# Generated by Django 2.2.18 on 2021-05-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0022_auto_20210507_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
