# Generated by Django 2.2.18 on 2021-05-07 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0023_delete_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='123456', max_length=50)),
                ('name', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('IDnumber', models.CharField(default='', max_length=20)),
                ('sex', models.CharField(default='', max_length=5)),
                ('entryTime', models.DateField(auto_now=True)),
                ('grade', models.IntegerField()),
                ('nation', models.IntegerField(default=0)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.ClassInfo')),
                ('native', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Cities')),
                ('outlook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Outlook')),
            ],
        ),
    ]
