# Generated by Django 2.2.18 on 2021-05-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0024_studentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='corgroup',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='adminstrator.TeacherInfo'),
        ),
        migrations.DeleteModel(
            name='Course_Group',
        ),
    ]
