# Generated by Django 2.2.18 on 2021-05-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0026_auto_20210508_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorinfo',
            name='course',
            field=models.ManyToManyField(to='adminstrator.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.CollegeInfo'),
        ),
    ]
