# Generated by Django 2.2.18 on 2021-05-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0028_auto_20210508_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='direct',
        ),
        migrations.CreateModel(
            name='Teacher2Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.ClassRoom')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Course')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.TeacherInfo')),
            ],
        ),
    ]
