# Generated by Django 2.2.18 on 2021-05-08 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0029_auto_20210508_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='native',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Cities'),
        ),
    ]
