# Generated by Django 2.2.18 on 2021-05-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0030_auto_20210508_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Teacher_title'),
        ),
    ]
