# Generated by Django 2.2.18 on 2021-05-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0031_auto_20210509_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.FloatField(),
        ),
    ]
