# Generated by Django 2.2.18 on 2021-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0032_auto_20210509_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hourperweek',
            field=models.FloatField(default=1.0),
        ),
    ]
