# Generated by Django 2.2.18 on 2021-05-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0033_course_hourperweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.IntegerField()),
                ('examtime', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.StudentInfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.TeacherInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher2Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.ClassRoom')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Course')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.TeacherInfo')),
                ('time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.ClassTime')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher2Course',
        ),
    ]
