# Generated by Django 2.2.18 on 2021-05-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0034_auto_20210509_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isfinished', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.StudentInfo')),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='elecourse',
            field=models.ManyToManyField(through='adminstrator.Student2Course', to='adminstrator.Course'),
        ),
    ]
