# Generated by Django 2.2.18 on 2021-05-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0035_auto_20210509_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfo4tc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
