# Generated by Django 2.2.18 on 2021-05-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0036_collegeinfo4tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminstrator.CollegeInfo4tc'),
        ),
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.CollegeInfo4tc'),
        ),
    ]
