# Generated by Django 2.2.18 on 2021-05-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0037_auto_20210509_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='college',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='adminstrator.CollegeInfo4tc'),
        ),
    ]
