# Generated by Django 2.2.18 on 2021-05-10 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0038_auto_20210509_1111'),
    ]

"""     operations = [
        migrations.AddField(
            model_name='course',
            name='pre_cou',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Course'),
        ),
    ] """
