# Generated by Django 2.2.18 on 2021-05-10 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0044_auto_20210510_0107'),
    ]

"""     operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_cou',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Course'),
        ),
    ] """
