# Generated by Django 2.2.18 on 2021-05-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0047_auto_20210510_0117'),
    ]

"""     operations = [
        migrations.RenameField(
            model_name='course',
            old_name='pre_cou',
            new_name='pre_co',
        ),
    ]
 """