# Generated by Django 2.2.18 on 2021-05-10 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0048_auto_20210510_0118'),
    ]

"""     operations = [
        migrations.RemoveField(
            model_name='course',
            name='pre_cou',
        ),
        migrations.AddField(
            model_name='course',
            name='pre_co',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='adminstrator.ClassRoom'),
        ),
    ]
 """