# Generated by Django 2.2.18 on 2021-05-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0049_auto_20210510_0118'),
    ]

"""     operations = [
        migrations.RemoveField(
            model_name='course',
            name='pre_cou',
        ),
    ] """
