# Generated by Django 2.2.18 on 2021-05-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0052_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='direct',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
