# Generated by Django 2.2.18 on 2021-05-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0053_auto_20210512_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Building'),
        ),
    ]
