# Generated by Django 2.2.18 on 2021-05-12 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0054_classroom_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='entryTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
