# Generated by Django 2.2.18 on 2021-05-14 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0057_auto_20210514_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='finishtime',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 19, 10, 38, 27903)),
        ),
        migrations.AlterField(
            model_name='message',
            name='gettime',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 19, 10, 38, 27880)),
        ),
    ]
