# Generated by Django 2.2.18 on 2021-05-14 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0059_auto_20210514_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='finishtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 12, 2, 46, 79883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='gettime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 12, 2, 46, 61368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='isFinished',
            field=models.IntegerField(default=0),
        ),
    ]
