# Generated by Django 2.2.18 on 2021-05-14 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0060_auto_20210514_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fromwho',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='finishtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 15, 3, 58, 892003, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='gettime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 15, 3, 58, 891978, tzinfo=utc)),
        ),
    ]
