# Generated by Django 2.2.18 on 2021-05-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0062_auto_20210514_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-isFinished', ['-gettime'], ['-finishtie']]},
        ),
    ]
