# Generated by Django 2.2.18 on 2021-04-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='123456', max_length=50)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
