# Generated by Django 2.2.18 on 2021-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='stu_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
