# Generated by Django 2.2.18 on 2021-04-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210425_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='StudentInfo',
        ),
    ]
