# Generated by Django 2.2.18 on 2021-04-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210425_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
